plugins:
  - 'prettier'
  - '@typescript-eslint'
  - 'react'
  - 'react-hooks'

extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'next/core-web-vitals'

parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
